Make API key required in config
statelyai/sky pull request #13
Opened 2023-11-11 16:50 UTC by davidkpiano

To simplify the API and make it possible to run multiple machines from different projects, we shouldn't implicitly grab the API key from `.env`, but instead do what other APIs do, which is require them directly.

We should direct users to put these API keys in their environment variables file and then read it in via `process.env.ANY_API_KEY_VAR`.

2023-11-11 23:35 UTC, gavination requested changes

2023-11-11 23:35 UTC, gavination commented on packages/sky-core/src/utils.ts
> +let SKY_HOST = 'stately-sky-beta.mellson.partykit.dev';
Don't think this hardcoded value should be here, no?

2023-11-13 08:31 UTC, mellson requested changes
I think this is a good change. Can you:

1. Also update the [`env.ts`](https://github.com/statelyai/sky/blob/main/packages/sky-core/src/env.ts) file to reflect the change
2. Revert the `yarn-error` & `pnpm-lock` files.
3. We also need to update [the documentation](https://stately.ai/docs/stately-sky-getting-started) to reflect this, would you like me to handle that part?

2023-11-13 08:36 UTC, mellson commented
> ... and make it possible to run multiple machines from different projects
We need to update the `xstate sky` cmd for this to work properly. I've created [STA-5554](https://linear.app/statelyai/issue/STA-5554) for this work.

2023-11-13 08:36 UTC, mellson commented on packages/sky-core/src/utils.ts
> +let SKY_HOST = 'stately-sky-beta.mellson.partykit.dev';
It's fine, it should be there 👍🏻

2023-11-13 09:58 UTC, mellson commented on packages/sky-core/src/actorFromStately.ts
>    if (!apiKey) {
This if block can now be removed

2023-11-13 09:59 UTC, mellson commented on vite-env.d.ts
> -    VITE_SKY_API_URL?: string;
We want to keep `VITE_SKY_API_URL`

2023-11-13 10:03 UTC, mellson commented
@davidkpiano Instead of you having to handle all our comments here I opened a new PR with this change here #14

2023-11-13 10:03 UTC, closed without merging